### ISSUE TITLE
How to set Authorization for web socket

### ISSUE THREAD

**Issue by bvanhou** [icarus-sullivan/lawcket#2]
As per your example:
```
const auth = (originalEvent) => {
    const { requestContext, headers } = originalEvent;
    if (headers && headers.Authorization 
        && requestContext.eventType === 'CONNECT') {
        // check authorization here
    }
    
    // middleware must return the event if not throwing
    return originalEvent;
}
```

I am using wscat `wscat -c ws://localhost:3001`

How do you set the Auth header

**Comment by icarus-sullivan** [comment]
[From the wscat documentation:](https://www.npmjs.com/package/wscat)

Looks like you need to pass it as an argument using the following convention 

```shell
wscat -c ws://localhost:3001 -H "Authorization:Bearer {token}"
```

**Comment by icarus-sullivan** [comment]
@bvanhou I'm going to be deprecating this library shortly in favor of a rewrite, which doesn't modify the incoming event so heavily. 

The new library can be found here: 
[@teleology/lambda-ws](https://www.npmjs.com/package/@teleology/lambda-ws)

**Comment by bvanhou** [comment]
Thanks
